version: '3.8'

services:
  backend:
    build: ./src
    container_name: backend-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_database
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password
      FRONTEND_URL: "http://localhost:3000/"
    volumes:
      - ./uploads:/usr/share/nginx/uploads
    networks:
      - backend-network
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  nginx:
    build: ./nginx
    container_name: nginx-service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/usr/share/nginx/uploads
    ports:
      - "80:80"
    networks:
      - backend-network

volumes:
  postgres_data:
  uploads:

networks:
  backend-network:
    driver: bridge
