services:
  - type: web
    name: backend-service
    env: docker
    buildCommand: ""
    startCommand: "java -jar /path/to/backend.jar" # Укажите команду запуска вашего backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://postgres:5432/my_database
      - key: SPRING_DATASOURCE_USERNAME
        value: my_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: my_password
      - key: FRONTEND_URL
        value: "http://nginx-service.onrender.com/" # URL Nginx-сервиса
    routes:
      - type: HTTP
        source: /
        targetPort: 8080 # Backend порт
    volumes:
      - name: uploads
        mountPath: /usr/share/nginx/uploads

  - type: web
    name: nginx-service
    env: docker
    buildCommand: ""
    startCommand: "" # Если команда запуска не указана, Render выполнит запуск по умолчанию
    dockerfilePath: ./nginx/Dockerfile
    routes:
      - type: HTTP
        source: /
        targetPort: 80
    volumes:
      - name: uploads
        mountPath: /usr/share/nginx/uploads

  - type: database
    name: postgres
    plan: standard
    databaseName: my_database
    user: my_user
    password: my_password
volumes:
  - name: uploads
